# Generated by Django 5.1 on 2024-08-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=255)),
                ('f_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('work', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Imageuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('employ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employees')),
            ],
        ),
    ]
